### ISSUE TITLE
Suggestions for a Better Testing Environment

### ISSUE THREAD

**Issue by SonYoungsung** [tokamak-network/gem-marketplace#28]
1. It would be helpful to have a way to directly obtain units or rare-grade items for testing, rather than relying on random packs.
2. The cooldown for mining is too long for testing purposes. Adjusting the time to fit the testing environment would allow users to stay engaged and quickly try the mining process, leading to more meaningful tests and participation.

**Comment by parth-tokamak** [comment]
Hey @SonYoungsung 

1. we have listed few Rare, Unique, Epic Gems for Sale so you can buy and test easily 

2. We have just lower the Cooldown Period for each rarirty
<img width="370" alt="image" src="https://github.com/user-attachments/assets/24688151-c446-4792-b567-b221a77ae4e2" />

NOTE:- In order to directly get TON on Thanos you can use this Account to transfer some TON to your testing Account
Private Key:- 2c6282bd8ef0aa9afffe625c88c454d949fe170473af483e5e996f7a89ab975d
